sonar.host.url=https://sonarcloud.io
sonar.organization=usdot-fhwa-stol
sonar.projectKey=usdot-fhwa-stol_connectedvcs-tools-test
sonar.projectName=connectedvcs-tools-test

sonar.sources=\
fedgov-cv-ISDcreator-webapp/src/main,\
fedgov-cv-TIMcreator-webapp/src/main,\
fedgov-cv-message-validator-webapp/src/main,\
fedgov-cv-asn1decoder/src/main/java,\
fedgov-cv-lib-asn1c/src/main/java,\
fedgov-cv-map-services-proxy/src/main/java,\
fedgov-cv-mapencoder/src/main/java,\
fedgov-cv-message-builder/src/main/java,\
fedgov-cv-rgaencoder/src/main/java,\
fedgov-cv-map-georeferencing/src/main/java,\
fedgov-cv-timencoder/src/main/java

sonar.tests=\
fedgov-cv-asn1decoder/src/test/java,\
fedgov-cv-mapencoder/src/test/java,\
fedgov-cv-timencoder/src/test/java,\
fedgov-cv-rgaencoder/src/test/java,\
fedgov-cv-map-services-proxy/src/test/java,\
fedgov-cv-map-georeferencing/src/test/java,\
fedgov-cv-message-builder/src/test/java

sonar.exclusions=**/target/**,tomcat/**,**/external/openlayers2/**

sonar.coverage.exclusions=\
fedgov-cv-ISDcreator-webapp/src/main/webapp/**,\
fedgov-cv-TIMcreator-webapp/src/main/webapp/**,\
fedgov-cv-message-validator-webapp/src/main/webapp/**,\
root/**

sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

sonar.junit.reportPaths=\
fedgov-cv-asn1decoder/target/surefire-reports,\
fedgov-cv-lib-asn1c/target/surefire-reports,\
fedgov-cv-mapencoder/target/surefire-reports,\
fedgov-cv-timencoder/target/surefire-reports,\
fedgov-cv-rgaencoder/target/surefire-reports,\
fedgov-cv-map-services-proxy/target/surefire-reports,\
fedgov-cv-map-georeferencing/target/surefire-reports,\
fedgov-cv-message-builder/target/surefire-reports

sonar.java.binaries=\
fedgov-cv-asn1decoder/target/classes,\
fedgov-cv-lib-asn1c/target/classes,\
fedgov-cv-map-services-proxy/target/classes,\
fedgov-cv-mapencoder/target/classes,\
fedgov-cv-message-builder/target/classes,\
fedgov-cv-rgaencoder/target/classes,\
fedgov-cv-map-georeferencing/target/classes,\
fedgov-cv-timencoder/target/classes

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
