sonar.host.url=https://sonarcloud.io
sonar.organization=usdot-fhwa-stol
sonar.projectKey=usdot-fhwa-stol_connectedvcs-tools
sonar.projectName=connectedvcs-tools

sonar.sources=\
fedgov-cv-ISDcreator-webapp/src/main,\
fedgov-cv-TIMcreator-webapp/src/main,\
fedgov-cv-asn1decoder/src/main,\
fedgov-cv-lib-asn1c/src/main,\
fedgov-cv-map-services-proxy/src/main,\
fedgov-cv-mapencoder/src/main,\
fedgov-cv-message-builder/src/main,\
fedgov-cv-message-validator-webapp/src/main,\
fedgov-cv-rgaencoder/src/main,\
fedgov-cv-timencoder/src/main

sonar.tests=\
fedgov-cv-asn1decoder/src/test,\
fedgov-cv-mapencoder/src/test,\
fedgov-cv-timencoder/src/test,\
fedgov-cv-rgaencoder/src/test,\
fedgov-cv-map-services-proxy/src/test,\
fedgov-cv-message-builder/src/test

sonar.exclusions=**/target/**,tomcat/**,**/external/openlayers2/**

sonar.coverage.exclusions=**/src/test/**,fedgov-cv-lib-asn1c/**,fedgov-cv-ISDcreator-webapp/**,fedgov-cv-message-validator-webapp/**,fedgov-cv-TIMcreator-webapp/**

sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

sonar.junit.reportPaths=\
fedgov-cv-asn1decoder/target/surefire-reports,\
fedgov-cv-mapencoder/target/surefire-reports,\
fedgov-cv-timencoder/target/surefire-reports,\
fedgov-cv-rgaencoder/target/surefire-reports,\
fedgov-cv-map-services-proxy/target/surefire-reports,\
fedgov-cv-message-builder/target/surefire-reports

sonar.java.binaries=\
fedgov-cv-ISDcreator-webapp/target/classes,\
fedgov-cv-TIMcreator-webapp/target/classes,\
fedgov-cv-asn1decoder/target/classes,\
fedgov-cv-lib-asn1c/target/classes,\
fedgov-cv-map-services-proxy/target/classes,\
fedgov-cv-mapencoder/target/classes,\
fedgov-cv-message-builder/target/classes,\
fedgov-cv-message-validator-webapp/target/classes,\
fedgov-cv-rgaencoder/target/classes,\
fedgov-cv-timencoder/target/classes

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-