name: connectedvcs-tools
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [develop, master, fix_sonar_setup]
env:
  working-directory: $GITHUB_WORKSPACE
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Sonar token used to get sonar cloud reports
jobs:
    Build:
      runs-on: ubuntu-latest
      container:
        image: maven:3.8.5-jdk-8-slim
        options: --user root
      steps:
        - name: Install deps
          run: |
            apt-get update -y
            apt-get -y install wget unzip sudo git

        - name: Checkout ${{ github.event.repository.name }}
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Install # This action is to install and build subfolders in project
          run: |
            cd $GITHUB_WORKSPACE
            export LD_LIBRARY_PATH=/__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-lib-asn1c/third_party_lib
            cd /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-parent && mvn -B -fae -e -X clean verify
            cd /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-lib-asn1c && mvn -B -fae -e -X clean verify
            cd /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-asn1decoder && mvn -B -fae -e -X clean verify
            cd /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-mapencoder && mvn -B -fae -e -X clean verify
            cd /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-rgaencoder && mvn -B -fae -e -X clean verify
            cd /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-message-builder && mvn -B -fae -e -X clean verify
            cd /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-ISDcreator-webapp && mvn -B -fae -e -X clean verify
            cd /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-message-validator-webapp && mvn -B -fae -e -X clean verify
            cd /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-TIMcreator-webapp && mvn -B -fae -e -X clean verify
            cd /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-map-services-proxy && mvn -B -fae -e -X clean verify
            jar cvf /__w/connectedvcs-tools/connectedvcs-tools/root.war -C /__w/connectedvcs-tools/connectedvcs-tools/root .
        - name: Archive generated Class files
          uses: actions/upload-artifact@v4 # Archive the generated class files after the build action used for deployment
          with:
            name: Class files
            path: |
              /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-message-builder/target/classes
              /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-message-builder/target/test-classes
        - name: SonarCloud scan
          uses: SonarSource/sonarcloud-github-action@v2
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dproject.settings=.sonarqube/sonar-scanner.properties
        - name: Download Apache tomcat # Download apache tomcat for deployment
          run: |
            wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.34/bin/apache-tomcat-9.0.34.tar.gz
            tar -xzf apache-tomcat-9.0.34.tar.gz
            mv apache-tomcat-9.0.34 tomcat
            rm -rf tomcat/webapps/ROOT
            rm -rf tomcat/webapps/docs
            rm -rf tomcat/webapps/examples
            rm -rf tomcat/webapps/host-manager
            rm -rf tomcat/webapps/manager
            rm -f apache-tomcat-9.0.34.tar.gz
        - name: Configure webapp # Configure the tomcat webapp with moving the files to tomcat dir's
          run: |
            mkdir -p tomcat/webapps/connectedvcs-tools/ROOT/WEB-INF/classes
            mv $GITHUB_WORKSPACE/root/WEB-INF/web.xml /__w/connectedvcs-tools/connectedvcs-tools/tomcat/webapps/connectedvcs-tools/ROOT/WEB-INF/
            mv $GITHUB_WORKSPACE/root/index.html /__w/connectedvcs-tools/connectedvcs-tools/tomcat/webapps/connectedvcs-tools/
            mv -n $GITHUB_WORKSPACE/root/* /__w/connectedvcs-tools/connectedvcs-tools/tomcat/webapps/connectedvcs-tools/ROOT/
            cp /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-TIMcreator-webapp/target/tim.war /__w/connectedvcs-tools/connectedvcs-tools/tomcat/webapps/
            cp /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-ISDcreator-webapp/target/isd.war /__w/connectedvcs-tools/connectedvcs-tools/tomcat/webapps/
            cp /__w/connectedvcs-tools/connectedvcs-tools/fedgov-cv-message-validator-webapp/target/validator.war /__w/connectedvcs-tools/connectedvcs-tools/tomcat/webapps/
            cp /__w/connectedvcs-tools/connectedvcs-tools/root.war /__w/connectedvcs-tools/connectedvcs-tools/tomcat/webapps/
        - uses: actions/setup-java@v3 # This action is to setup Java
          with:
            distribution: 'temurin'
            java-version: '17'
            check-latest: true
        -  name: Configure network and set privileges # This action is to set newtork privileges on tomact server
           run: |
            sed -i '/<\/Engine>/ i \ \ \ \ \  <Host name="connectedvcs-tools" appBase="webapps/connectedvcs-tools" unpackWARs="true" autoDeploy="true">\n      </Host>' tomcat/conf/server.xml
            echo -e '127.0.0.1\connectedvcs-tools' | sudo tee -a /etc/hosts
            sudo groupadd tomcat
            sudo useradd -g tomcat -m tomcat
            chmod g+r tomcat/conf/*
            chmod -R o-rwx tomcat/webapps/*
            sudo chown -R root:tomcat tomcat
            sudo chown -R tomcat:tomcat tomcat/logs
            sudo chown -R tomcat:tomcat tomcat/temp
            sudo chown -R tomcat:tomcat tomcat/work
        - name: Start Tomcat and verify deployment
          run: |
            mv setenv.sh /__w/connectedvcs-tools/connectedvcs-tools/tomcat/bin/
            sudo /__w/connectedvcs-tools/connectedvcs-tools/tomcat/bin/catalina.sh start
